[Centos]
Centos01	ansible_host=192.168.10.11
Centos02	ansible_host=192.168.10.12

[Ubuntu]
Ubuntu01	ansible_host=192.168.10.21
Ubuntu02	ansible_host=192.168.10.22

[linux:children]
Centos
Ubuntu

[appserver:children]
Ubuntu

[fileserver]
nfs01	ansible_host=192.168.10.11

